// Code generated by protoc-gen-go.
// source: template.proto
// DO NOT EDIT!

/*
Package template is a generated protocol buffer package.

It is generated from these files:
	template.proto

It has these top-level messages:
	BasicDataTypes
	EnumType
	OtherType
*/
package template

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Color int32

const (
	Color_white Color = 0
	Color_red   Color = 1
	Color_green Color = 2
)

var Color_name = map[int32]string{
	0: "white",
	1: "red",
	2: "green",
}
var Color_value = map[string]int32{
	"white": 0,
	"red":   1,
	"green": 2,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}
func (Color) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BasicDataTypes struct {
	Int32Type  int32   `protobuf:"varint,1,opt,name=int32Type" json:"int32Type,omitempty"`
	DoubleType float64 `protobuf:"fixed64,2,opt,name=doubleType" json:"doubleType,omitempty"`
	BoolType   bool    `protobuf:"varint,3,opt,name=boolType" json:"boolType,omitempty"`
	StringType string  `protobuf:"bytes,4,opt,name=stringType" json:"stringType,omitempty"`
}

func (m *BasicDataTypes) Reset()                    { *m = BasicDataTypes{} }
func (m *BasicDataTypes) String() string            { return proto.CompactTextString(m) }
func (*BasicDataTypes) ProtoMessage()               {}
func (*BasicDataTypes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BasicDataTypes) GetInt32Type() int32 {
	if m != nil {
		return m.Int32Type
	}
	return 0
}

func (m *BasicDataTypes) GetDoubleType() float64 {
	if m != nil {
		return m.DoubleType
	}
	return 0
}

func (m *BasicDataTypes) GetBoolType() bool {
	if m != nil {
		return m.BoolType
	}
	return false
}

func (m *BasicDataTypes) GetStringType() string {
	if m != nil {
		return m.StringType
	}
	return ""
}

type EnumType struct {
	Color Color `protobuf:"varint,1,opt,name=color,enum=template.Color" json:"color,omitempty"`
}

func (m *EnumType) Reset()                    { *m = EnumType{} }
func (m *EnumType) String() string            { return proto.CompactTextString(m) }
func (*EnumType) ProtoMessage()               {}
func (*EnumType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EnumType) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_white
}

type OtherType struct {
	Color Color    `protobuf:"varint,1,opt,name=color,enum=template.Color" json:"color,omitempty"`
	Array []string `protobuf:"bytes,2,rep,name=array" json:"array,omitempty"`
}

func (m *OtherType) Reset()                    { *m = OtherType{} }
func (m *OtherType) String() string            { return proto.CompactTextString(m) }
func (*OtherType) ProtoMessage()               {}
func (*OtherType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OtherType) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_white
}

func (m *OtherType) GetArray() []string {
	if m != nil {
		return m.Array
	}
	return nil
}

func init() {
	proto.RegisterType((*BasicDataTypes)(nil), "template.BasicDataTypes")
	proto.RegisterType((*EnumType)(nil), "template.EnumType")
	proto.RegisterType((*OtherType)(nil), "template.OtherType")
	proto.RegisterEnum("template.Color", Color_name, Color_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TemplateService service

type TemplateServiceClient interface {
	BasicDataTypesRequest(ctx context.Context, in *BasicDataTypes, opts ...grpc.CallOption) (*BasicDataTypes, error)
	EnumTypeRequest(ctx context.Context, in *EnumType, opts ...grpc.CallOption) (*EnumType, error)
	OtherTypeRequest(ctx context.Context, in *OtherType, opts ...grpc.CallOption) (*OtherType, error)
}

type templateServiceClient struct {
	cc *grpc.ClientConn
}

func NewTemplateServiceClient(cc *grpc.ClientConn) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) BasicDataTypesRequest(ctx context.Context, in *BasicDataTypes, opts ...grpc.CallOption) (*BasicDataTypes, error) {
	out := new(BasicDataTypes)
	err := grpc.Invoke(ctx, "/template.TemplateService/BasicDataTypesRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) EnumTypeRequest(ctx context.Context, in *EnumType, opts ...grpc.CallOption) (*EnumType, error) {
	out := new(EnumType)
	err := grpc.Invoke(ctx, "/template.TemplateService/EnumTypeRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) OtherTypeRequest(ctx context.Context, in *OtherType, opts ...grpc.CallOption) (*OtherType, error) {
	out := new(OtherType)
	err := grpc.Invoke(ctx, "/template.TemplateService/OtherTypeRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TemplateService service

type TemplateServiceServer interface {
	BasicDataTypesRequest(context.Context, *BasicDataTypes) (*BasicDataTypes, error)
	EnumTypeRequest(context.Context, *EnumType) (*EnumType, error)
	OtherTypeRequest(context.Context, *OtherType) (*OtherType, error)
}

func RegisterTemplateServiceServer(s *grpc.Server, srv TemplateServiceServer) {
	s.RegisterService(&_TemplateService_serviceDesc, srv)
}

func _TemplateService_BasicDataTypesRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicDataTypes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).BasicDataTypesRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.TemplateService/BasicDataTypesRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).BasicDataTypesRequest(ctx, req.(*BasicDataTypes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_EnumTypeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).EnumTypeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.TemplateService/EnumTypeRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).EnumTypeRequest(ctx, req.(*EnumType))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_OtherTypeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtherType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).OtherTypeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.TemplateService/OtherTypeRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).OtherTypeRequest(ctx, req.(*OtherType))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "template.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BasicDataTypesRequest",
			Handler:    _TemplateService_BasicDataTypesRequest_Handler,
		},
		{
			MethodName: "EnumTypeRequest",
			Handler:    _TemplateService_EnumTypeRequest_Handler,
		},
		{
			MethodName: "OtherTypeRequest",
			Handler:    _TemplateService_OtherTypeRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}

func init() { proto.RegisterFile("template.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xdd, 0xd6, 0x68, 0x32, 0x87, 0x24, 0x8c, 0x0a, 0x25, 0x88, 0x48, 0x40, 0x11, 0x0f,
	0x05, 0xd3, 0x93, 0xe0, 0xc9, 0x3f, 0x20, 0x78, 0x10, 0xd6, 0xbe, 0xc0, 0x26, 0x1d, 0xda, 0x40,
	0x9a, 0x8d, 0x9b, 0x8d, 0xd2, 0x57, 0xf0, 0x05, 0x7d, 0x1d, 0x93, 0xad, 0x49, 0x5a, 0xa8, 0x07,
	0x8f, 0xdf, 0xf7, 0xfb, 0x66, 0xf8, 0x76, 0x58, 0x70, 0x35, 0x2d, 0x8b, 0x4c, 0x68, 0x1a, 0x17,
	0x4a, 0x6a, 0x89, 0x76, 0xab, 0xc3, 0x2f, 0x06, 0xee, 0xbd, 0x28, 0xd3, 0xe4, 0x51, 0x68, 0x31,
	0x5d, 0x15, 0x54, 0xe2, 0x29, 0x38, 0x69, 0xae, 0x27, 0x51, 0xa3, 0x46, 0xec, 0x9c, 0x5d, 0x59,
	0xbc, 0x37, 0xf0, 0x0c, 0x60, 0x26, 0xab, 0x38, 0x23, 0x83, 0x07, 0x35, 0x66, 0x7c, 0xc3, 0xc1,
	0x00, 0xec, 0x58, 0xca, 0xcc, 0xd0, 0x61, 0x4d, 0x6d, 0xde, 0xe9, 0x66, 0xb6, 0xd4, 0x2a, 0xcd,
	0xe7, 0x86, 0xee, 0xd7, 0xd4, 0xe1, 0x1b, 0x4e, 0x78, 0x03, 0xf6, 0x53, 0x5e, 0x2d, 0x4d, 0xf6,
	0x02, 0xac, 0x44, 0x66, 0x52, 0x99, 0x06, 0x6e, 0xe4, 0x8d, 0xbb, 0x27, 0x3c, 0x34, 0x36, 0x5f,
	0xd3, 0xf0, 0x19, 0x9c, 0x57, 0xbd, 0x20, 0xf5, 0x8f, 0x19, 0x3c, 0x06, 0x4b, 0x28, 0x25, 0x56,
	0x75, 0xfb, 0x61, 0xdd, 0x60, 0x2d, 0xae, 0x2f, 0xc1, 0x32, 0x29, 0x74, 0xc0, 0xfa, 0x5c, 0xa4,
	0x9a, 0xfc, 0x3d, 0x3c, 0x84, 0xa1, 0xa2, 0x99, 0xcf, 0x1a, 0x6f, 0xae, 0x88, 0x72, 0x7f, 0x10,
	0x7d, 0x33, 0xf0, 0xa6, 0xbf, 0x7b, 0xdf, 0x48, 0x7d, 0xa4, 0x09, 0xe1, 0x0b, 0x9c, 0x6c, 0x1f,
	0x91, 0xd3, 0x7b, 0x45, 0xa5, 0xc6, 0x51, 0x5f, 0x61, 0x3b, 0x10, 0xfc, 0x49, 0xf0, 0x16, 0xbc,
	0xf6, 0x0a, 0xed, 0x1a, 0xec, 0xc3, 0x2d, 0x0a, 0x76, 0x78, 0x78, 0x07, 0x7e, 0x77, 0x8d, 0x76,
	0xf6, 0xa8, 0xcf, 0x75, 0x2c, 0xd8, 0x65, 0xc6, 0x07, 0xe6, 0x73, 0x4c, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x38, 0x6e, 0x25, 0x27, 0x2e, 0x02, 0x00, 0x00,
}
